server:
  port: 8081

spring:
  application:
    name: BILLING-SERVICE
  datasource:
    url: ${DB_URL}
    username:  ${DB_USERNAME}
    password:  ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
